// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOO_Ox6WXz72tz7oQb3DDoarw0qRK-E5Y',
    appId: '1:670623270254:android:34140786cfdea4e5c7ad7f',
    messagingSenderId: '670623270254',
    projectId: 'mech-ar-1387a',
    databaseURL: 'https://mech-ar-1387a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mech-ar-1387a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfOZTUJh7be7kfrsr46qEGn2Ntpystz0U',
    appId: '1:670623270254:ios:746c0c79c88b7b23c7ad7f',
    messagingSenderId: '670623270254',
    projectId: 'mech-ar-1387a',
    databaseURL: 'https://mech-ar-1387a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mech-ar-1387a.appspot.com',
    androidClientId: '670623270254-rcoatmfv1qbb9e69cj9vbhj1anlbqti0.apps.googleusercontent.com',
    iosClientId: '670623270254-cqbkua838l0dtdjnt5605kjar578672c.apps.googleusercontent.com',
    iosBundleId: 'com.example.resq',
  );

}