// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9_EDvwHbHck165mS12-95GyB9VKWA3DM',
    appId: '1:1025376246778:android:311f7ed4faeba02c07a243',
    messagingSenderId: '1025376246778',
    projectId: 'resqapp-3d47d',
    databaseURL: 'https://resqapp-3d47d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resqapp-3d47d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0718WAxHl9LvBIgujpnKPNUjYbLiiknk',
    appId: '1:1025376246778:ios:87e4bc977ddb695807a243',
    messagingSenderId: '1025376246778',
    projectId: 'resqapp-3d47d',
    databaseURL: 'https://resqapp-3d47d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resqapp-3d47d.firebasestorage.app',
    iosBundleId: 'com.example.resqapp',
  );
}
